# Generated by Django 3.1.11 on 2021-05-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210520_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knockout',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='quarterfinal',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='semifinal',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='final',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='knockout',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quarterfinal',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='semifinal',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
