# Generated by Django 3.1.11 on 2021-05-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SemiFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.PositiveSmallIntegerField(blank=True, choices=[('TEAM 1', 1), ('TEAM 2', -1), ('NULL', 0)], null=True)),
                ('date', models.DateTimeField()),
                ('team1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sf_host', to='schedule.team')),
                ('team2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sf_opponent', to='schedule.team')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.PositiveSmallIntegerField(blank=True, choices=[('TEAM 1', 1), ('TEAM 2', -1), ('NULL', 0)], null=True)),
                ('date', models.DateTimeField()),
                ('team1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qf_host', to='schedule.team')),
                ('team2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qf_opponent', to='schedule.team')),
            ],
        ),
        migrations.CreateModel(
            name='KnockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.PositiveSmallIntegerField(blank=True, choices=[('TEAM 1', 1), ('TEAM 2', -1), ('NULL', 0)], null=True)),
                ('date', models.DateTimeField()),
                ('team1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ko_host', to='schedule.team')),
                ('team2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ko_opponent', to='schedule.team')),
            ],
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.PositiveSmallIntegerField(blank=True, choices=[('TEAM 1', 1), ('TEAM 2', -1), ('NULL', 0)], null=True)),
                ('date', models.DateTimeField()),
                ('team1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_host', to='schedule.team')),
                ('team2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_opponent', to='schedule.team')),
            ],
        ),
    ]
