# Generated by Django 3.1.11 on 2021-05-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210519_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='winner',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'TEAM 1'), (-1, 'TEAM 2'), (0, 'NULL')], null=True),
        ),
        migrations.AlterField(
            model_name='knockout',
            name='winner',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'TEAM 1'), (-1, 'TEAM 2'), (0, 'NULL')], null=True),
        ),
        migrations.AlterField(
            model_name='quarterfinal',
            name='winner',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'TEAM 1'), (-1, 'TEAM 2'), (0, 'NULL')], null=True),
        ),
        migrations.AlterField(
            model_name='semifinal',
            name='winner',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'TEAM 1'), (-1, 'TEAM 2'), (0, 'NULL')], null=True),
        ),
    ]
